// js/data.js – Base de données des événements

const EVENTS = [
  {
    id: 1,
    title: "AfroFest 2025",
    category: "Concert",
    emoji: "🎵",
    color: "#1a0a00",
    date: "14 Juin 2025",
    time: "19h00",
    location: "Stade du 4-Août, Ouagadougou",
    price: 5000,
    stock: 200,
    description: "Le plus grand festival de musique africaine de Ouagadougou revient pour une édition explosive. Artistes locaux et internationaux au rendez-vous.",
  },
  {
    id: 2,
    title: "TechSummit Burkina",
    category: "Conférence",
    emoji: "💼",
    color: "#001a0d",
    date: "22 Juin 2025",
    time: "08h30",
    location: "Hôtel Azalai, Ouagadougou",
    price: 15000,
    stock: 80,
    description: "La conférence tech incontournable du Burkina Faso. Startups, innovation numérique, IA et entrepreneuriat au programme.",
  },
  {
    id: 3,
    title: "Coupe du Faso Finale",
    category: "Sport",
    emoji: "⚽",
    color: "#00001a",
    date: "5 Juillet 2025",
    time: "16h00",
    location: "Stade Municipal, Bobo-Dioulasso",
    price: 2000,
    stock: 5,
    description: "La grande finale de la Coupe Nationale du Faso. Vivez l'atmosphère électrique de ce match tant attendu.",
  },
  {
    id: 4,
    title: "Festival du Cinéma Africain",
    category: "Festival",
    emoji: "🎬",
    color: "#1a001a",
    date: "18 Juillet 2025",
    time: "17h00",
    location: "Centre Culturel Français, Ouagadougou",
    price: 3000,
    stock: 120,
    description: "Projections de films, masterclasses avec des réalisateurs africains et soirées de gala. Une immersion dans le cinéma du continent.",
  },
  {
    id: 5,
    title: "Stand-Up Comedy Night",
    category: "Spectacle",
    emoji: "🎭",
    color: "#1a0a0a",
    date: "2 Août 2025",
    time: "20h00",
    location: "L'Espace Culturel Gambidi, Ouagadougou",
    price: 4000,
    stock: 60,
    description: "Une soirée d'humour avec les meilleurs comédiens du Burkina et de la sous-région. Rires garantis !",
  },
  {
    id: 6,
    title: "Marathon de Ouagadougou",
    category: "Sport",
    emoji: "🏃",
    color: "#001a1a",
    date: "15 Août 2025",
    time: "06h00",
    location: "Place de la Nation, Ouagadougou",
    price: 1000,
    stock: 500,
    description: "Participez au marathon annuel de la capitale ! Plusieurs catégories disponibles : 5km, 10km et marathon complet.",
  },
];
